In [1]:
import torch

2.创建一个未初始化的5*3张量

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


3.创建一个随机初始化的5x3张量

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0801, 0.4210, 0.7537],
        [0.6363, 0.6512, 0.0150],
        [0.2934, 0.3261, 0.0642],
        [0.7838, 0.8918, 0.3337],
        [0.3920, 0.9250, 0.6538]])


4.创建一个5x3的0张量，类型为long

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


5.直接从数组创建张量

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


8.打印一个张量的维度

In [6]:
print(x.size())

torch.Size([2])


9.将两个张量相加

In [8]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)
# 方法二
# print(torch.add(x, y))

# 方法三
#result = torch.empty(5, 3)
#torch.add(x, y, out=result)
#print(result)

# 方法四
#y.add_(x)
#print(y)

tensor([[0.9921, 0.5630, 1.7244],
        [1.2444, 0.7067, 0.3822],
        [1.6567, 1.2736, 1.2341],
        [0.9766, 1.7017, 0.7610],
        [1.4401, 0.6894, 1.2523]])


11.将一个4x4的张量resize成一个一维张量

In [10]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
print(x.size(),y.size())

tensor([[-0.9950, -0.1812,  0.0982,  0.8423],
        [ 1.5947,  0.2146, -0.9827,  0.9254],
        [ 0.6175,  1.3210, -0.7575, -1.3204],
        [ 1.0631,  0.0438,  0.1843, -0.6128]])
tensor([-0.9950, -0.1812,  0.0982,  0.8423,  1.5947,  0.2146, -0.9827,  0.9254,
         0.6175,  1.3210, -0.7575, -1.3204,  1.0631,  0.0438,  0.1843, -0.6128])
torch.Size([4, 4]) torch.Size([16])


12.将一个4x4的张量，resize成一个2x8的张量

In [14]:
y = x.view(2, 8)
print(x.size(),y.size())
print(x)
print(y)
# 方法二
z = x.view(-1, 8) # 确定一个维度，-1的维度会被自动计算
print(x.size(),z.size())

torch.Size([4, 4]) torch.Size([2, 8])
tensor([[-0.9950, -0.1812,  0.0982,  0.8423],
        [ 1.5947,  0.2146, -0.9827,  0.9254],
        [ 0.6175,  1.3210, -0.7575, -1.3204],
        [ 1.0631,  0.0438,  0.1843, -0.6128]])
tensor([[-0.9950, -0.1812,  0.0982,  0.8423,  1.5947,  0.2146, -0.9827,  0.9254],
        [ 0.6175,  1.3210, -0.7575, -1.3204,  1.0631,  0.0438,  0.1843, -0.6128]])
torch.Size([4, 4]) torch.Size([2, 8])


13.从张量中取出数字

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0257])
-1.0256909132003784


14.将张量装换成numpy数组

In [19]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


15.将张量+1，并观察上题中numpy数组的变化

In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


16.从numpy数组创建张量

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


17.将numpy数组+1并观察上题中张量的变化

In [22]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


18.新建一个张量，并设置requires_grad=True

In [23]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


19.对张量进行任意操作（y = x + 2）

In [24]:
y = x + 2
print(y)
print(y.grad_fn) # y就多了一个AddBackward的对象

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


20.再对y进行任意操作

In [25]:
z = y * y * 3
out = z.mean()

print(z) # z多了MulBackward的对象
print(out) # out多了MeanBackward的对象

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


21.对out进行反向传播

In [26]:
out.backward()

22.打印梯度d(out)/dx

In [27]:
print(x.grad) #out=0.25*Σ3(x+2)^2

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
